## script combining the analysis of the blood and blister data from the agile trial
## using cytovi (as opposed to catalyst in R)


## checking the gpu set up
```{python}
import torch
import torchmetrics
print(torch.__version__)
print(torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
```

```{python}
import os
import random
import tempfile
import glob

import matplotlib.pyplot as plt  # type: ignore
from matplotlib import rcParams
import numpy as np  # type: ignore
import requests
import scanpy as sc  # type: ignore
import pandas as pd
import scvi
import torch  # type: ignore
from rich import print  # type: ignore
from scvi.external import cytovi  # type: ignore
import seaborn as sns
import seaborn.objects as so
from plotnine import *
import statsmodels.formula.api as smf

os.environ["SCIPY_ARRAY_API"] = "1"

sc.set_figure_params(figsize=(4, 4))

scvi.settings.seed = 0
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
print("Last run with scvi-tools version:", scvi.__version__)
```

## tell scvi to use gpu where relevant (apparently this should spped up the heavy steps 10-50x!)
```{python}
scvi.settings.device = "cuda"
scvi.settings.seed = 0
```

## load in all fcs files from current working directory, excluding certain channels and not creating a sample column yet (whole file name will still be stored at this point)
```{python}
adata = cytovi.read_fcs(".", remove_markers=["FSC - Area", "SSC - Area", "Time Stamp", "Live-dead : Zombie-NIR - Area"], sample_name_extractor=None)
```

## make a new sample_full column that is the file name minus the redundant suffix
## also change the phrasing the blood data from "stained_blood" to just "blood"
```{python}
adata.obs["sample_full"] = adata.obs["filename"].str.replace(" WLSM_CD45 Pos.fcs", "", regex=False)
adata.obs["sample_full"] = adata.obs["sample_full"].str.replace("stained_blood", "blood", regex=False)
adata.obs
```

## now split the sample name by underscores (this contains donor, treatment, time etc) and then make these new columns
```{python}
parts = adata.obs["sample_full"].str.split("_", expand=True)
adata.obs["treatment"] = parts[0]
adata.obs["donor"]     = parts[1]
adata.obs["tissue"]    = parts[2]
adata.obs["time"]      = parts[3]
adata.obs
```

## rename tissue groupings, as they are currently slightly different
```{python}
adata.obs["tissue"] = adata.obs["tissue"].map(
    {
        "blood":"blood",
        "blister":"blister",
        "Blister":"blister",
        "Blister1":"blister",
        "Blister2":"blister"
    }
)
```

```{python}
# -----------------------------
# 2Subsample blood cells proportionally
# -----------------------------
# Separate tissues
blister_cells = adata[adata.obs['tissue'] == "blister"].copy()
blood_cells = adata[adata.obs['tissue'] == "blood"].copy()

# Total number of blood cells to keep for plotting
target_blood_n = 100_000

# Compute proportions per donor
sample_counts = blood_cells.obs['sample_full'].value_counts()
sample_props = sample_counts / sample_counts.sum()

blood_subsample = []

for sample, prop in sample_props.items():
    sample_idx = blood_cells.obs[blood_cells.obs['sample_full'] == sample].index
    n_keep = int(np.round(prop * target_blood_n))
    if len(sample_idx) > n_keep:
        chosen = np.random.choice(sample_idx, size=n_keep, replace=False)
    else:
        chosen = sample_idx
    blood_subsample.extend(chosen)

# Combine with all blister cells
subset_idx = np.concatenate([blister_cells.obs.index, blood_subsample])
adata = adata[subset_idx].copy()
adata.obs.groupby(["tissue", "time"]).size()
```

## perform arcsinh transformation with a cofactor of 2000 (recommended in multiple tutorials)
```{python}
cytovi.transform_arcsinh(adata, global_scaling_factor=2000)
cytovi.scale(adata)
```

## free up memory
```{python}
import gc
gc.collect()
```

## rename markers 
```{python}
var_series = pd.Series(adata.var_names)
clean_names = var_series.str.split(":", expand=True)[0].str.strip()
adata.var_names = clean_names.values
```

## plot marker expression for inspection
```{python}
cytovi.plot_histogram(adata, marker="all", groupby="tissue", layer_key="scaled")
cytovi.plot_biaxial(adata, marker_x="CD3", marker_y="CD8", color="tissue", layer_key="scaled")
```

## save object here
```{python}
#adata.write("agile_combined_pre_model.h5ad")
adata = sc.read_h5ad("agile_combined_pre_model.h5ad")
```

## set up and train the cytovi model
```{python}
cytovi.CYTOVI.setup_anndata(adata, layer="scaled", batch_key="donor")
model = cytovi.CYTOVI(adata)
model.train(n_epochs_kl_warmup=20, max_epochs=100, batch_size=1024)
```

```{python}
plt.figure()
plt.plot(model.history["elbo_train"], label="Train")
plt.figure()
plt.plot(model.history["elbo_validation"], label="Validation")
plt.xlabel("Epochs")
plt.ylabel("ELBO")
plt.legend()
plt.title("Training vs Validation ELBO")
plt.show()
```

## add the new cytovi embedding
## compute neighbours
## 
```{python}
adata.obsm["X_CytoVI"] = model.get_latent_representation()
sc.pp.neighbors(adata, use_rep="X_CytoVI", n_neighbors=30)
```

```{python}
sc.tl.umap(adata)
sc.pl.umap(adata, color="tissue")
```

```{python}
adata.layers["imputed"] = model.get_normalized_expression()
```

```{python}
adata.write("agile_combined_modelled.h5ad")
adata = sc.read_h5ad("agile_combined_modelled.h5ad")
```

```{python}
sc.pl.umap(adata, color=["tissue", "time"])
```

```{python}
g = cytovi.plot_histogram(
    adata, marker=["CD62L", "CD16", "CD69"], layer_key="scaled", groupby="tissue", return_plot=True
)
g.fig.suptitle("Uncorrected expression", fontsize=16)

h = cytovi.plot_histogram(
    adata, marker=["CD62L", "CD16", "CD69"], layer_key="imputed", groupby="tissue", return_plot=True
)
h.fig.suptitle("Corrected expression", fontsize=16)
```

```{python}
plt.figure()
marker_umaps = sc.pl.umap(adata, color=adata.var_names, layer="imputed", ncols=5, cmap="mako", show=False, vmax="p99")
plt.savefig("marker_umaps.png", dpi=300)
```

```{python}
for res in [0.4,0.5,0.6,0.7,0.8,0.9,1]:
    sc.tl.leiden(adata, resolution=res, key_added="leiden_res_"+str(res), flavor="igraph")
sc.pl.umap(adata, color=["leiden_res_0.7", "leiden_res_0.8", "leiden_res_0.9", "leiden_res_1"], legend_loc="on data", frameon = False, size =5)
```

```{python}
sc.pl.umap(adata, color=["leiden_res_1"], size=5, legend_loc="on data")
sc.pl.umap(adata, color=["tissue", "time", "treatment"], size=5)
```

```{python}
sc.pl.matrixplot(
    adata,
    var_names=["CD3", "CD4", "CD8", "FOXP3", "CD25", "CD56", "CD14", "CD16", "CD1c", "HLA-DR", "CD66b", "CD15", "CD62L", "CD20"],
    groupby="leiden_res_1",
    layer="imputed",
    dendrogram=True,
    standard_scale="var",
    cmap="Reds",
)
```

```{python}
sc.pl.stacked_violin(adata, var_names=["CD3", "CD4", "CD8", "CD20", "CD14", "CD16", "FOXP3"], groupby="leiden_res_1", layer="scaled", stripplot=False, use_raw=False)
```

```{python}
potential_neuts= adata[adata.obs["leiden_res_1"].isin(["12","20","25","22","30", "27", "28", "29"])].copy()
cytovi.plot_histogram(
    potential_neuts, marker=["CD62L", "CD16", "CD184", "CD15", "CD182"], layer_key="imputed", groupby="leiden_res_1", return_plot=True
)
```

```{python}
potential_mono= adata[adata.obs["leiden_res_1"].isin(["5", "7", "23", "8", "17", "16"])].copy()
cytovi.plot_histogram(
    potential_mono, marker=["CD14", "CD16", "HLA-DR", "CD1c"], layer_key="imputed", groupby="leiden_res_1", return_plot=True
)
```
```{python}
prop_table = (
    adata.obs
        .pivot_table(index="donor", columns="leiden_res_1", aggfunc="size", fill_value=0)
)

# Convert counts to proportions
prop_table = prop_table.div(prop_table.sum(axis=1), axis=0)

# Plot stacked bar chart
fig, ax = plt.subplots(figsize=(12,6))

prop_table.plot(
    kind="bar",
    stacked=True,
    ax=ax,
    colormap="tab20"
)

ax.set_ylabel("Proportion of cells")
ax.set_xlabel("Donor")
ax.set_title("Cell-type proportions per donor")
ax.tick_params(axis='x', rotation=45)

ax.legend(
    title="Cell type",
    bbox_to_anchor=(0.5, -0.25),   # center below plot
    loc='upper center',
    ncol=8,                        # number of columns in legend (adjust as needed)
    frameon=False
)
```

```{python}
cell_annotation_dict = {
    "0": "CD8+T_blister",
    "1": "CD8+T_blister",
    "2": "NK_blister",
    "3": "CD4+T_blister",
    "4": "Treg_blister",
    "5": "DC_blister",
    "6": "CD8+T_blister",
    "7": "DC_blister",
    "8": "CD1c+_blister",
    "9": "CD8+T_blister",
    "10": "CD8+T_blister",
    "11": "CD8+T_blister",
    "12": "Neutrophil_aged_blister",
    "13": "CD8+T_blood",
    "14": "Debris/doublets",
    "15": "NK_blister",
    "16": "CD8+T_blood",
    "17": "DC(CD1c-)_blood",
    "18": "Debris/doublets",
    "19": "NK_blood",
    "20": "Neutrophil_aged_blister",
    "21": "CD4+T_blood",
    "22": "Neutrophil_young_blood",
    "23": "Classical_mono_blood",
    "24": "Invariant_T_blister",
    "25": "Neutrophil_mature_blister",
    "26": "CD4+T_blood",
    "27": "Neutrophil_aged_blood",
    "28": "Neutrophil_mature_blood",
    "29": "Neutrophil_mature_blood",
    "30": "Neutrophil_mature_blood"
}

adata.obs["label"] = adata.obs["leiden_res_1"].map(cell_annotation_dict)
cluster_palette= ["indianred", "green", "limegreen", "darkorchid", "purple", "darkred", "red", "chocolate", "grey", "hotpink", "goldenrod", "darkgoldenrod", "deepskyblue", "blue", "darkblue", "darkcyan", "cyan", "greenyellow"]
```

## save/load here
```{python}
#adata.write("agile_combined_annotated.h5ad")
adata = sc.read_h5ad("agile_combined_annotated.h5ad")
```

```{python}
rcParams["figure.figsize"] = (10, 10)
plt.figure()
sc.pl.umap(adata, color="label", legend_loc="on data", legend_fontoutline=2, frameon = False, size =5, palette=cluster_palette, legend_fontsize="small", title="annotated UMAP")
plt.savefig("UMAP_annotated.png", dpi=300, bbox_inches="tight")
```

```{python}
#sc.tl.dendrogram(adata, groupby="label")
plt.figure()
sc.pl.matrixplot(
    adata,
    var_names=["CD3", "CD4", "CD8", "FOXP3", "CD56", "CD14", "CD16", "CD1c", "HLA-DR", "CD66b", "CD15", "CD62L"],
    groupby="label",
    layer="imputed",
    dendrogram=True,
    standard_scale="var",
    cmap="Reds",
    figsize=(12,7)
)
plt.savefig("annotated_heatmap.png", dpi=300)
```

## do a second heatmap without debris/doublets and the invariant t cells (as these dominate the sacale of some markers)
```{python}
remove = ["Debris/doublets", "Invariant_T_blister"]
adata_trim = adata[~adata.obs["label"].isin(remove)].copy()
sc.tl.dendrogram(adata_trim, groupby="label")
plt.figure()
sc.pl.matrixplot(
    adata_trim,
    var_names=["CD3", "CD4", "CD8", "FOXP3", "CD56", "CD14", "CD16", "CD1c", "HLA-DR", "CD66b", "CD15", "CD62L"],
    groupby="label",
    layer="imputed",
    dendrogram=True,
    standard_scale="var",
    cmap="Reds",
    figsize=(12,7)
)
plt.savefig("annotated_heatmap_trimmed.png", dpi=300)
```
## some treatment names are wrong so unifying
## make sure 4h times are combined with 6h
```{python}
treatment_dict = {
    "Guinness":"Guinness",
    "guinness":"Guinness",
    "Corona":"Corona",
    "corona":"Corona"
}

adata.obs["treatment_clean"] = adata.obs["treatment"].map(treatment_dict)


time_dict = {
    "-72h":"-72h",
    "0h":"0h",
    "4h":"6h",
    "6h":"6h",
    "24h":"24h",
    "48h":"48h",
    "72h":"72h"
}
adata.obs["time_clean"] = adata.obs["time"].map(time_dict)
```

```{python}
df = adata.obs

counts = df.groupby(["label", "tissue"]).size().unstack(fill_value=0)
props  = counts.div(counts.sum(axis=1), axis=0).reset_index().melt(
    id_vars="label",
    var_name="tissue",
    value_name="prop"
)
p = so.Plot(props, y="label", x = "prop", color="tissue").add(so.Bar(), so.Stack())
fig=p.plot()._figure
fig.savefig("tissue_cluster_proportions.png", dpi=300, bbox_inches="tight")
```

```{python}
plt.figure()
sc.pl.umap(adata, color=["tissue", "donor", "treatment"], size=5)
plt.savefig("umap_metadata.png",dpi=300,bbox_inches="tight")
```

## plotting neut markers across neut clusters to see how different
```{python}
labels_to_keep = [
    "Neutrophil_mature_blood",
    "Neutrophil_mature_blister",
    "Neutrophil_aged_blood",
    "Neutrophil_young_blood",
    "Neutrophil_aged_blister"
]

adata_sub = adata[adata.obs["label"].isin(labels_to_keep)].copy()
sc.pl.stacked_violin(adata_sub, var_names=["CD16", "CD62L"], groupby="label", layer = "imputed", swap_axes=True)
```

```{python}
df = adata.obs.copy()
cluster_to_remove = "Debris/doublets"
df = df[df["label"] != cluster_to_remove].copy()

df_blood = df[df["tissue"] == "blood"].copy()
df_blister = df[df["tissue"] == "blister"].copy()


# Count cells per donor × time × treatment × label
blood_counts = (
    df_blood.groupby(["donor", "time_clean", "treatment_clean", "label"])
      .size()
      .reset_index(name="count")
)

# Compute proportions within each donor × time × treatment
blood_counts["prop"] = blood_counts.groupby(["donor", "time_clean", "treatment_clean"])["count"].transform(lambda x: x / x.sum()*100)

# Count cells per donor × time × treatment × label
blister_counts = (
    df_blister.groupby(["donor", "time_clean", "treatment_clean", "label"])
      .size()
      .reset_index(name="count")
)

# Compute proportions within each donor × time × treatment
blister_counts["prop"] = blister_counts.groupby(["donor", "time_clean", "treatment_clean"])["count"].transform(lambda x: x / x.sum()*100)

```

```{python}
#blood
time_order = ["-72h", "0h", "6h", "24h", "48h", "72h"]
blood_counts['time_clean'] = pd.Categorical(
    blood_counts['time_clean'],
    categories=time_order,
    ordered=True
)
blood_counts = blood_counts.dropna(subset=['prop'])
blood_counts = blood_counts[blood_counts['label'].str.contains("blood", case=False)]
if pd.api.types.is_categorical_dtype(blood_counts['label']):
    blood_counts['label'] = blood_counts['label'].cat.remove_unused_categories()
#blister
time_order = ["6h", "24h", "48h", "72h"]
blister_counts['time_clean'] = pd.Categorical(
    blister_counts['time_clean'],
    categories=time_order,
    ordered=True
)

blister_counts = blister_counts.dropna(subset=['prop'])
blister_counts = blister_counts[blister_counts['label'].str.contains("blister", case=False)]
if pd.api.types.is_categorical_dtype(blister_counts['label']):
    blister_counts['label'] = blister_counts['label'].cat.remove_unused_categories()
```

## export dataframes for use in an R script to perform lmer
```{python}
blood_counts.to_csv("agile_blood_proportions_df.csv", index=False)
blister_counts.to_csv("agile_blister_proportions_df.csv", index=False)
```

```{python}
sc.pl.dotplot(adata, ["CD3", "CD4", "CD8", "FOXP3", "CD56", "CD14", "CD16", "CD1c", "HLA-DR", "CD66b", "CD15", "CD62L"], groupby="label", dendrogram=True, layer="imputed", standard_scale="var")
```
```{python}
plt.figure()
sc.pl.correlation_matrix(adata, "label", figsize=(10,10))
plt.savefig("cluster_correlation.png", dpi=500, bbox_inches="tight")
```

```{python}
# Convert relevant data to a dataframe
df = adata.obs.copy()
expr = pd.DataFrame(adata.layers["imputed"], index=adata.obs_names, columns=adata.var_names)
df = pd.concat([df, expr], axis=1)

df.to_csv("agile_combined_expression_df.csv")

sample_check = pd.DataFrame(df["sample_full"].unique())
```